CREATE TABLE agc_trace_sequence (
    trace_id VARCHAR(128) NOT NULL PRIMARY KEY,
    next_seq BIGINT NOT NULL
);

CREATE TABLE agc_audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(128) NOT NULL,
    sequence_num BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    decision_type VARCHAR(16),
    reason_code VARCHAR(256),
    matched_rule_ids VARCHAR(2048),
    decision_details VARCHAR(4000),
    tool_name VARCHAR(512),
    payload_summary VARCHAR(4000) NOT NULL,
    payload_hash VARCHAR(128),
    CONSTRAINT uq_agc_audit_trace_seq UNIQUE (trace_id, sequence_num)
);

CREATE INDEX idx_agc_audit_trace ON agc_audit_event (trace_id, sequence_num);
